// This file is generated by Slice Machine. Update with care!

import CodeBlock from './CodeBlock';
import Image from './Image';
import Text from './Text';

export {
	CodeBlock,
	Image,
	Text,
};

export const components = {
	code_block: CodeBlock,
	image: Image,
	text: Text,
};
